# Site settings
title: "Servo Blog"
description: ""
url: "http://anidata.org"
baseurl: ""
google_analytics:

#  Build settings
permalink: "/blog/:categories/:year/:month/:day/:title.html"
#paginate_path: "/blog/page:num"
#paginate: 3

gems:
    - jekyll-redirect-from
    - jekyll-paginate
